site:
  name: 'AFC JJB - Abdoulaev Fighters Club'
  site: 'https://afc-jjb.fr'
  base: '/' 
  trailingSlash: false
  googleSiteVerificationId: 'PXVwqcO6DnafJP3z105rluW9yB9taZPw0inQc6QCWEQ'

# ğŸŒ SEO & MÃ©tadonnÃ©es pour Google et les rÃ©seaux sociaux
metadata:
  title:
    default: 'AFC JJB - Jiu-Jitsu BrÃ©silien, Grappling, Pancrace & MMA Ã  Quimper'
    template: '%s | AFC JJB'
  description: 'DÃ©couvrez lâ€™AFC JJB, un club de Jiu-Jitsu BrÃ©silien, Grappling, Pancrace et MMA Ã  Quimper. EntraÃ®nements pour dÃ©butants et confirmÃ©s avec des coachs expÃ©rimentÃ©s.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'AFC JJB - Jiu-Jitsu BrÃ©silien, Grappling et Pancrace Ã  Quimper'
    images:
      - url: 'https://afc-jjb.fr/images/logo-final-web.png'
        width: 1200
        height: 628
    type: website
  social:
    instagram: 'https://www.instagram.com/afc_jjb/'
    tiktok: 'https://www.tiktok.com/@afc_jjb'
    facebook: 'https://www.facebook.com/groups/1794363377995046'

# ğŸŒ ParamÃ¨tres de langue
i18n:
  language: fr
  textDirection: ltr

# ğŸš€ Optimisation UI
ui:
  theme: 'system' # Valeurs: "system" | "light" | "dark" | "light:only" | "dark:only"

# ğŸ“Š Google Analytics (Mettre ton ID si activÃ©)
analytics:
  vendors:
    googleAnalytics:
      id: null # Ajouter ton ID Google Analytics si activÃ©

# ğŸš« DÃ©sactivation du blog (tu n'en as pas besoin)
apps:
  blog:
    isEnabled: false
