site:
  name: 'AFC JJB - Abdoulaev Fighters Club'
  site: 'https://afc-jjb.fr'
  base: '/' 
  trailingSlash: false
  googleSiteVerificationId: 'PXVwqcO6DnafJP3z105rluW9yB9taZPw0inQc6QCWEQ'

# üåç SEO & M√©tadonn√©es pour Google et les r√©seaux sociaux
metadata:
  title:
    default: 'AFC JJB - Jiu-Jitsu Br√©silien, Grappling, Pancrace & MMA √† Quimper'
    template: '%s | AFC JJB'
  description: 'D√©couvrez l‚ÄôAFC JJB, un club de Jiu-Jitsu Br√©silien, Grappling, Pancrace et MMA √† Quimper. Entra√Ænements pour d√©butants et confirm√©s avec des coachs exp√©riment√©s.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'AFC JJB - Jiu-Jitsu Br√©silien, Grappling et Pancrace √† Quimper'
    images:
      - url: 'https://afc-jjb.fr/images/logo-final-web.png'
        width: 1483
        height: 1349
    type: website
  social:
    instagram: 'https://www.instagram.com/afc_jjb/'
    tiktok: 'https://www.tiktok.com/@afc_jjb'
    facebook: 'https://www.facebook.com/profile.php?id=61573992897299'

# üåç Param√®tres de langue
i18n:
  language: fr
  textDirection: ltr

# üöÄ Optimisation UI
ui:
  theme: 'system' # Valeurs: "system" | "light" | "dark" | "light:only" | "dark:only"

analytics:
  vendors:
    googleAnalytics:
      id: "G-N4D74QPBB0"  # Remplace par ton propre ID


# üö´ D√©sactivation du blog (tu n'en as pas besoin)
apps:
  blog:
    isEnabled: false
